version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: argueos_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: argueos_local
    ports:
      - "5433:5432"  # <--- CHANGE THIS LINE (5433 on left)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: